#!/usr/bin/env bash
# Fetch + PIN the model files into $KYC_MODELS_DIR, verifying EVERY artifact against a
# REQUIRED SHA256. Fail-closed: a missing pin or a hash mismatch aborts the whole run
# (set -euo pipefail). Nothing is committed to git — models live in the image/volume,
# reproducible by hash. Writes $KYC_MODELS_DIR/MODELS.lock; verify_models.sh re-checks
# it at container boot so a tampered/mismatched volume cannot serve.
#
# AV-S1 (planset 2026-07-16-kyc-autoverify): replaces the previous "warn-and-continue"
# posture (buffalo_l auto-fetched with NO integrity check; anti_spoof SHA optional).
set -euo pipefail
DEST="${KYC_MODELS_DIR:-/models}"
mkdir -p "$DEST"

# Portable SHA256 (Linux image: sha256sum; macOS dev/CI: shasum -a 256).
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}';
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}
require_sha() { # $1 file, $2 expected-hex
  local got; got="$(sha256_of "$1")"
  if [ "$got" != "$2" ]; then
    echo "[models] FATAL: SHA256 mismatch for $1" >&2
    echo "         expected $2" >&2
    echo "         got      $got" >&2
    exit 1
  fi
  echo "[models] OK  $(basename "$1")  $got"
}

# --- buffalo_l (SCRFD detect + ArcFace embed): pinned zip, verified, then extracted ---
# We fetch the release zip OURSELVES and verify it, rather than letting insightface
# auto-download it unverified on first prepare(). Default URL is the upstream v0.7
# release; override with KYC_BUFFALO_L_URL if you mirror it. The SHA is REQUIRED — the
# operator pins it once from a trusted fetch (see README "Pinning buffalo_l").
: "${KYC_BUFFALO_L_SHA256:?set KYC_BUFFALO_L_SHA256 — the pinned SHA256 of buffalo_l.zip (no default; pin it)}"
BUF_URL="${KYC_BUFFALO_L_URL:-https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip}"
mkdir -p "$DEST/models"
echo "[models] fetching buffalo_l.zip from $BUF_URL …"
curl -fsSL "$BUF_URL" -o "$DEST/buffalo_l.zip"
require_sha "$DEST/buffalo_l.zip" "$KYC_BUFFALO_L_SHA256"
# Upstream buffalo_l.zip holds the .onnx files at the archive root; insightface expects
# them under $root/models/buffalo_l/. Extract there so prepare() finds them (no re-fetch).
python - <<'PY'
import os, zipfile
dest = os.environ.get("KYC_MODELS_DIR", "/models")
target = os.path.join(dest, "models", "buffalo_l")
with zipfile.ZipFile(os.path.join(dest, "buffalo_l.zip")) as z:
    z.extractall(target)
print(f"buffalo_l extracted -> {target}")
PY
rm -f "$DEST/buffalo_l.zip"

# --- anti-spoof (Silent-Face MiniFASNet) ONNX: pinned, SHA now REQUIRED (fail-closed) ---
: "${KYC_ANTISPOOF_URL:?set KYC_ANTISPOOF_URL to your chosen anti-spoof .onnx}"
: "${KYC_ANTISPOOF_SHA256:?set KYC_ANTISPOOF_SHA256 — the pinned SHA256 (no longer optional)}"
echo "[models] fetching anti_spoof.onnx …"
curl -fsSL "$KYC_ANTISPOOF_URL" -o "$DEST/anti_spoof.onnx"
require_sha "$DEST/anti_spoof.onnx" "$KYC_ANTISPOOF_SHA256"

# --- write the lockfile the boot-time verifier (verify_models.sh) re-checks ---
# Format per line: "<sha256>  <relpath-under-KYC_MODELS_DIR>". Comment lines start with #.
{
  echo "# VERI model lock — generated by download_models.sh. DO NOT hand-edit."
  echo "# Re-checked at container boot by verify_models.sh (fail-closed)."
  echo "$KYC_ANTISPOOF_SHA256  anti_spoof.onnx"
  # Record every extracted buffalo_l model file so boot-time verify catches tampering
  # of the individual .onnx weights, not just the (now-deleted) zip.
  find "$DEST/models/buffalo_l" -type f -name '*.onnx' | sort | while read -r f; do
    echo "$(sha256_of "$f")  ${f#"$DEST"/}"
  done
} > "$DEST/MODELS.lock"
echo "[models] wrote $DEST/MODELS.lock"
echo "[models] done → $DEST"
